---
title: "Ordination analysis - Transferred objects"
author: "Carlos Riera-Ruiz"
date: "2023-10-02"
output:
  pdf_document: default
  html_document: default
  
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '.')
getwd()
```

```{r create phyloseq object with original data of all viruses}
library(phyloseq)
library(microbiome)
library(microViz)
otu_original<-"TO_otu_table_transferred.csv"
meta_original<-"TO_meta_table_transferred.csv"
tax_original<-"TO_tax_table_transferred.csv"

tax_with_lengths<-"TO_tax_table_with_lengths.csv"

# import otu table
#otu table
otu<-read.table(otu_original, header=T, row.names=1, check.names=F, sep=",")
OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
OTU_phy = phyloseq(OTU)
#meta data
meta<-read.table(meta_original, header=T, row.names=1, check.names=F, sep=",")
meta$Person<-gsub("_","_0",meta$Person)
meta$Person<-gsub("_010","_10",meta$Person)
#meta$Person<-paste0("P_",meta$Person)
meta_phy = sample_data(data.frame(meta, row.names=sample_names(OTU_phy), stringsAsFactors=FALSE))
meta_phy$Type<-as.factor(meta_phy$Type)
meta_phy$Person<-as.factor(meta_phy$Person)
meta_phy$Day<-as.factor(meta_phy$Day)
meta_phy$Object<-as.factor(meta_phy$Object)
meta_phy$Object2<-as.factor(meta_phy$Object2)
meta_phy$Group1<-as.factor(meta_phy$Group1)
#tax table
tax<-read.table(tax_original, header=T, row.names=1, check.names=F, sep=",")

# create phyloseq
OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
OTU_phy = phyloseq(OTU)
meta_phy = sample_data(data.frame(meta, row.names=sample_names(OTU_phy), stringsAsFactors=FALSE))
tax_phy=tax_table(as.matrix(tax))
ps = merge_phyloseq(OTU_phy[,colSums(OTU_phy)>0], meta_phy, tax_phy)
ps

```

```{r make phyloseq object with only objects}
samples_to_keep<-c("Hands","Ceramic","Plastic","Knife","Phone","Glass")
ps_only_objects<-subset_samples(ps, Object %in% samples_to_keep & Day %in% c(0))
ps_only_objects<-subset_samples(ps, Object %in% samples_to_keep)
ps_only_objects

```

```{r}

ps_relative <- transform_sample_counts(ps_only_objects, function(x) x/sum(x) )
sample_data(ps_relative)$Object = factor(sample_data(ps_relative)$Object, levels = samples_to_keep)
ps_relative

```

```{r get otu without contigs absent in hands}
ps_hands <- ps_filter(ps_only_objects, Object == "Hands")
ps_hands_contigs<-rownames(otu_table(ps_hands))
ps_hands_contigs
ps2 <- prune_taxa(ps_hands_contigs,ps)  # phyloseq objects with contigs present in hands only and shared with objects
ps2

#otu table
otu<-data.frame(ps2@otu_table)
OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
OTU_phy = phyloseq(OTU)
#meta data
meta<-data.frame(ps2@sam_data)
meta_phy = sample_data(data.frame(meta, row.names=sample_names(OTU_phy), stringsAsFactors=FALSE))
meta_phy$Type<-as.factor(meta_phy$Type)
meta_phy$Person<-as.factor(meta_phy$Person)
meta_phy$Day<-as.factor(meta_phy$Day)
meta_phy$Object<-as.factor(meta_phy$Object)
meta_phy$Object2<-as.factor(meta_phy$Object2)
meta_phy$Group1<-as.factor(meta_phy$Group1)
#tax table
tax<-data.frame(ps2@tax_table)

# create phyloseq
OTU = otu_table(as.matrix(otu), taxa_are_rows = TRUE)
OTU_phy = phyloseq(OTU)
meta_phy = sample_data(data.frame(meta, row.names=sample_names(OTU_phy), stringsAsFactors=FALSE))
tax_phy=tax_table(as.matrix(tax))
ps2 = merge_phyloseq(OTU_phy[,colSums(OTU_phy)>0], meta_phy, tax_phy)
ps2

library(microViz)
library(ggplot2)
library(vegan)

ps2 %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "aitchison", binary=TRUE, na.rm = TRUE) %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Person", shape = "Object2", size = 3)
#  scale_colour_brewer(palette = "Dark2")

ps2 %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "kulczynski", binary=TRUE, na.rm = TRUE) %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Person", shape = "Object2", size = 3)
#  scale_colour_brewer(palette = "Dark2")

dist_mat<-vegdist(t(otu_table(ps2)), method='kulczynski',na.rm=TRUE)
sample_data<-data.frame(sample_data(ps2))
#adonis2(dist_mat~as.factor(sample_data$Person) + as.factor(sample_data$Day) + as.factor(sample_data$Object), data=sample_data, permutations=999)
#adonis2(dist_mat~as.factor(sample_data$Person) + as.factor(sample_data$Object), data=sample_data, permutations=999, by = "margin")

ps2 %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "jaccard", binary=TRUE, na.rm = TRUE) %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Person", shape = "Object2", size = 3, axes = c(1,2))
#  scale_colour_brewer(palette = "Dark2")

ps2 %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "jaccard", binary=TRUE, na.rm = TRUE) %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Person", shape = "Object2", size = 3, axes = c(1,3))
#  scale_colour_brewer(palette = "Dark2")

ps2 %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "jaccard", binary=TRUE, na.rm = TRUE) %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Person", shape = "Object2", size = 3, axes = c(2,3))
#  scale_colour_brewer(palette = "Dark2")

dist_mat<-vegdist(t(otu_table(ps2)), method='jaccard',na.rm=TRUE)
sample_data<-data.frame(sample_data(ps2))
#adonis2(dist_mat~as.factor(sample_data$Person) + as.factor(sample_data$Day) + as.factor(sample_data$Object), data=sample_data, permutations=999)
adonis2(dist_mat~as.factor(sample_data$Person) + as.factor(sample_data$Object), data=sample_data, permutations=999, by = "margin")

ps2_relative <- transform_sample_counts(ps2, function(x) x / sum(x) )
ps2_relative %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "bray", na.rm = TRUE) %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Person", shape = "Object2", size = 3)
#  scale_colour_brewer(palette = "Dark2")

dist_mat<-vegdist(t(otu_table(ps2)), method='bray',na.rm=TRUE)
sample_data<-data.frame(sample_data(ps2))
#adonis2(dist_mat~as.factor(sample_data$Person) + as.factor(sample_data$Day) + as.factor(sample_data$Object), data=sample_data, permutations=999)
adonis2(dist_mat~as.factor(sample_data$Person) + as.factor(sample_data$Object), data=sample_data, permutations=999, by = "margin")



library("scatterplot3d")
# R colors https://www.datanovia.com/en/blog/awesome-list-of-657-r-color-names/

ps3_ord <- ps2 %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc(dist = "jaccard", binary=TRUE, na.rm = TRUE) %>%
  ord_calc("PCoA")
MDS1<-ps3_ord@ord$Ybar[,1]
MDS2<-ps3_ord@ord$Ybar[,2]
MDS3<-ps3_ord@ord$Ybar[,3]
sam_data<-data.frame(ps2@sam_data)

#sam_data<-sam_data[order(sam_data$Object2),]
sam_data$Object2<-as.factor(sam_data$Object2)
shapes = c(16, 17)
shapes<-shapes[as.numeric(sam_data$Object2)]

#col_by<-gsub("P_P_","P_",sam_data$Person)
col_by<-sam_data$Person
colors=c("brown1", "darkgoldenrod", "chartreuse4","aquamarine3","cyan3", "darkorchid","deeppink3")
data_3d<-data.frame(MDS1,MDS2,MDS3,col_by)
data_3d$col_by<-as.factor(data_3d$col_by)

col_by<-gsub("P_01","brown1",col_by)
col_by<-gsub("P_02","darkgoldenrod",col_by)
col_by<-gsub("P_03","chartreuse4",col_by)
col_by<-gsub("P_04","aquamarine3",col_by)
col_by<-gsub("P_06","cyan3",col_by)
col_by<-gsub("P_08","darkorchid",col_by)
col_by<-gsub("P_10","deeppink3",col_by)

angle1=55
#s3d <- scatterplot3d(data_3d[,1:3], angle=10, color=col_by, pch=19, box=FALSE)
source('http://www.sthda.com/sthda/RDoc/functions/addgrids3d.r')
# 2. Empty 3D scatter plot using pch=""
s3d <- scatterplot3d(data_3d[, 1:3], pch = shapes, angle=angle1, grid=FALSE, box=FALSE)
# 3. Add grids
addgrids3d(data_3d[, 1:3], grid = c("xy", "xz", "yz"), angle=angle1)
# 4. Add points
s3d$points3d(data_3d[, 1:3], col=col_by, pch = shapes)

legend(s3d$xyz.convert(-0.8, -0.4, .2), legend = levels(data_3d$col_by), col =  colors, pch = 18)
```





